### ISSUE TITLE
Are benchmark results available online

### ISSUE THREAD

**Issue by ogencoglu** [benchopt/benchmark_nnls#21]
Are benchmark results available online somewhere or do we actually have to run the benchmarks?

**Comment by mathurinm** [comment]
Hi @ogencoglu, published benchmarks results are available here : https://benchopt.github.io/results/ but they are limited in the case of NNLS, feel free to run your own configuration locally!

**Comment by ogencoglu** [comment]
Thanks for the swift reply.
