### ISSUE TITLE
do you have benchmark for one hot spars data for nnls?

### ISSUE THREAD

**Issue by Sandy4321** [benchopt/benchmark_nnls#6]
do you have benchmark for one hot spars data for nnls?

**Comment by agramfort** [comment]
No but it would be a welcomed addition. Do you have a dataset we could add ?

**Comment by Sandy4321** [comment]
you can start from this
https://www.kaggle.com/ananaymital/us-used-cars-dataset
us-used-cars-dataset 9 GB and 3 million  rows and 66 features 
predict price

seems it is the best in internet for now

**Comment by agramfort** [comment]
I would use a stochastic solver for such data. I don't think we have this here. Anything smaller than this?

**Comment by Sandy4321** [comment]
smaller ?
what is limit for your code?

**Comment by Sandy4321** [comment]
do you mean to use this code
https://github.com/guozhaosengzs/nnls
 for such a big file?

**Comment by Sandy4321** [comment]
but 
https://github.com/guozhaosengzs/nnls
is very limited in data  inputs - no multivariate data ?

**Comment by tomMoral** [comment]
I think adding a larger/more realistic dataset would be very nice.
I think what when @agramfort says it is too big, he is right as the proposed dataset has `3e6` samples, which is typically a good use case for stochastic algorithms.
Finding another dataset for one hot sparse data with ~50,000 samples, would be a nice addition to the existing benchmark.

As for the proposed dataset `us-used-car`, I think we could probably add it if we add a stochastic solver in this benchmark. This would be a very intersting addition.

**Comment by agramfort** [comment]
just try
https://scikit-learn.org/stable/auto_examples/linear_model/plot_nnls.html

are you aiming for a benchmark or just a solver that works for your data?

>
